### ISSUE TITLE
Include arrow-check as an Arrow library

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-check#13]
- [x] Repository settings

- [x] Gradle configuration: https://github.com/arrow-kt/arrow-check/pull/9

- [x] GitHub Actions: https://github.com/arrow-kt/arrow-check/pull/10

- [x] Add the library in the list of Arrow libraries for global integration checks: https://github.com/arrow-kt/arrow/pull/2126

- [x] Add the menu entry for API docs: https://github.com/arrow-kt/arrow-site/pull/36 and https://github.com/arrow-kt/arrow-site/pull/37

**Comment by rachelcarmena** [comment]
It's being published in OSS:

* https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/arrow-check/
* https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/arrow-check-kotlintest/

API docs are available for the next version:

* https://arrow-kt.io/docs/next/apidocs/arrow-check/
* https://arrow-kt.io/docs/next/apidocs/arrow-check-kotlintest/

**Comment by rachelcarmena** [comment]
It's being published in OSS:

* https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/arrow-check/
* https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/arrow-check-kotlintest/

API docs are available for the next version:

* https://arrow-kt.io/docs/next/apidocs/arrow-check/
* https://arrow-kt.io/docs/next/apidocs/arrow-check-kotlintest/

cc: @1Jajen1

**Comment by 1Jajen1** [comment]
Nice! Thanks :tada: 

Regarding the docs: There are places where we have documentation that isn't part of the api-docs. For example introductions, tutorials etc. Do those belong in arrow-site or is there some other place for them?

**Comment by rachelcarmena** [comment]
> Nice! Thanks tada

You're welcome :raised_hands: 

> Regarding the docs: There are places where we have documentation that isn't part of the api-docs. For example introductions, tutorials etc. Do those belong in arrow-site or is there some other place for them?

Those files are distributed in 4 repositories when following the initial repository content organization: arrow-core, arrow-fx, arrow-optics and arrow-incubator (take a look at https://github.com/arrow-kt/arrow-site/blob/master/README.md for their links). 

However, you could include documentation in the same way in this repository, just adding them in `arrow-docs/docs/` (that directory must be created) and then including their links in the sidebar (like https://github.com/arrow-kt/arrow-site/pull/36 and https://github.com/arrow-kt/arrow-site/pull/37).

**Comment by rachelcarmena** [comment]
Just waiting for a cache invalidation to show the right style for API doc. Closing it!
